package recipe

type AutoGenerated struct {
	From  int    `json:"from"`
	To    int    `json:"to"`
	Count int    `json:"count"`
	Links Links  `json:"_links"`
	Hits  []Hits `json:"hits"`
}
type Self struct {
	Href  string `json:"href"`
	Title string `json:"title"`
}
type Next struct {
	Href  string `json:"href"`
	Title string `json:"title"`
}
type Links struct {
	Self Self `json:"self"`
	Next Next `json:"next"`
}
type Ingredients struct {
	Text     string  `json:"text"`
	Quantity float64 `json:"quantity"`
	Measure  string  `json:"measure"`
	Food     string  `json:"food"`
	Weight   float64 `json:"weight"`
	FoodID   string  `json:"foodId"`
}
type TotalNutrients struct {
}
type TotalDaily struct {
}
type Sub struct {
	Label        string  `json:"label"`
	Tag          string  `json:"tag"`
	SchemaOrgTag string  `json:"schemaOrgTag"`
	Total        float64 `json:"total"`
	HasRDI       bool    `json:"hasRDI"`
	Daily        float64 `json:"daily"`
	Unit         string  `json:"unit"`
}
type Digest struct {
	Label        string  `json:"label"`
	Tag          string  `json:"tag"`
	SchemaOrgTag string  `json:"schemaOrgTag"`
	Total        float64 `json:"total"`
	HasRDI       bool    `json:"hasRDI"`
	Daily        float64 `json:"daily"`
	Unit         string  `json:"unit"`
	Sub          []Sub   `json:"sub"`
}
type Recipe struct {
	URI             string         `json:"uri"`
	Label           string         `json:"label"`
	Image           string         `json:"image"`
	Source          string         `json:"source"`
	URL             string         `json:"url"`
	ShareAs         string         `json:"shareAs"`
	Yield           float64        `json:"yield"`
	DietLabels      []string       `json:"dietLabels"`
	HealthLabels    []string       `json:"healthLabels"`
	Cautions        []string       `json:"cautions"`
	IngredientLines []string       `json:"ingredientLines"`
	Ingredients     []Ingredients  `json:"ingredients"`
	Calories        float64        `json:"calories"`
	TotalWeight     float64        `json:"totalWeight"`
	CuisineType     []string       `json:"cuisineType"`
	MealType        []string       `json:"mealType"`
	DishType        []string       `json:"dishType"`
	TotalNutrients  TotalNutrients `json:"totalNutrients"`
	TotalDaily      TotalDaily     `json:"totalDaily"`
	Digest          []Digest       `json:"digest"`
}
type Hits struct {
	Recipe Recipe `json:"recipe"`
	Links  Links  `json:"_links"`
}
